const fs = require('fs');
const logfile = fs.readFileSync()
const log = {
  playthrough: [],
  "Horon Village": {
    "maku tree": "",
    "horon village SE chest": "",
    "horon village SW chest": "",
    "shop, 150 rupees": "",
    "shop, 20 rupees": "",
    "shop, 30 rupees": "",
    "member's shop 1": "",
    "member's shop 2": "",
    "member's shop 3": "",    
  },
  "Western Coast": {
    "hero's cave key chest": "",
    "hero's cave rupee chest": "",
    "hero's cave sword chest": "",
    "black beast's chest": "",
  },
  "North Horon/Natze": {
    "dry eyeglass lake, east cave": "",
    "dry eyeglass lake, west cave": "",
    "eyeglass lake, across bridge": "",
    "natzu region, across water": "",
    "moblin keep": "",
  },
  "Horon Plains, Spool Swamp, Tarm Ruins": {
    "cave north of D1": "",
    "cave south of mrs. ruul": "",
    "old man in treehouse": "",
    "blaino's gym": "",
    "spool swamp cave": "",
    "tarm ruins, under tree": "",
    "lost woods": "",
  },
  "Eastern Suburbs, Desert, Woods of Winter": {
    "eastern suburbs, on cliff": "",
    "samasa desert chest": "",
    "samasa desert pit": "",
    "cave outside D2": "",
    "chest on top of D2": "",
    "holly's house": "",
    "woods of winter, 1st cave": "",
    "woods of winter, 2nd cave": "",
    "western coast, beach chest": "",
    "western coast, in house": "",
  },
  "Sunkin City": {
    "master diver's challenge": "",
    "master diver's reward": "",
    "chest in master diver's cave": "",
    "sunken city, summer cave": "",
  },
  "Moutain": {
    "diving spot outside D4": "",
    "goron mountain, across pits": "",
    "mt. cucco, platform cave": "",
    "mt. cucco, talon's cave": "",
    "chest in goron mountain": "",
    "spring banana tree": "",
  },
  "Subrosia": {
    "temple of seasons": "",
    "tower of autumn": "",
    "tower of spring": "",
    "tower of summer": "",
    "tower of winter": "",
    "great furnace": "",
    "subrosia village chest": "",
    "subrosia market, 1st item": "",
    "subrosia market, 2nd item": "",
    "subrosia market, 5th item": "",
    "subrosia seaside": "",
    "subrosian wilds chest": "",
    "subrosia, locked cave": "",
    "subrosia, open cave": "",
    "subrosian dance hall": "",
    "subrosian smithy": "",
  },
  "Seed Trees": {
    "horon village tree": "",
    "north horon tree": "",
    "woods of winter tree": "",
    "spool swamp tree": "",
    "sunken city tree": "",
    "tarm ruins tree": "",
  },
};

